library("biomaRt")
library("gdata")
library("Biostrings") # for using function DNAString # source("https://www.bioconductor.org/biocLite.R"),  biocLite("")
#install.packages("seqinr")
library("seqinr")
library("stringr")

## This script is to translate the fusion transcripts from confFuse prediction.

lenAA=14


fusionSeq="AAGATGAAGACAATGTTCTCAAAGCATTTACAGTACCTAAAAACAGGTCCCTGGCGAGCCCCTTGCAG|CTGAGGATTTGTGACTGGACCATGAATCAAAACGGCAGGCATTTATACCCCAGTA"

# reverse complement
# reverseComplement(DNAString("TAAAGAAGAGGCGGTAATTCTGCGAGCAGGGCTGGCCGCGCTCCTCAGTGTGGTACAGGGCCAT"))
## this is confirmed by published paper, FTVPKNRSLASPLQ | SWYLG*LGSFPSVK, break points: 135524462 MYB	14088325 NFIB, ACC_P11 , ACC_P14
fusionSeq2="TGTTCTCAAAGCATTTACAGTACCTAAAAACAGGTCCCTGGCGAGCCCCTTGCAG|TCCTGGTACCTGGGCTAGCTTGGTTCCTTTCCAAGTGTCAAATAGGACACCCATCTTAC"
## confirmed by published paper, FTVPKNRSLASPLQ | PTQPQAHLKPIDMW , break points: 135524462 MYB	14113080 NFIB, ACC_P11
fusionSeq1="GAAGATGAAGACAATGTTCTCAAAGCATTTACAGTACCTAAAAACAGGTCCCTGGCGAGCCCCTTGCAG|CCTACACAGCCTCAGGCACATCTCAAGCCAATCGATATGTGGGACTAAGCCCAAGAGACCCATCCTTCCTAC"
#### FTVPKNRSLASPLQ | LRICDWTMNQNGRH, break points: 135524462 MYB	14102509 NFIB, protein, identified in ACC_P18
fusionSeq3="GAAGATGAAGACAATGTTCTCAAAGCATTTACAGTACCTAAAAACAGGTCCCTGGCGAGCCCCTTGCAG|CTGAGGATTTGTGACTGGACCATGAATCAAAACGGCAGGCATTTATACCCCAG"

#### ACC_M9, NLLEFAETLQFIDS | LRICDWTMNQNGRH, break points: 135517140 MYB	14102509 NFIB; most reliable
f4="TAAGAACCTCTTAGAATTTGCAGAAACACTCCAATTTATAGATTCT|CTGAGGATTTGTGACTGGACCATGAATCAAAACGGCAGGCATTTATACCCCAGTAC"
#### ACC_M9, GLSPRDPSFLHQQQ | FLNTSSNHENSDLE, break points: 14112998 NFIB	135520046 MYB
f5="CCAATCGATATGTGGGACTAAGCCCAAGAGACCCATCCTTCCTACATCAGCAACAG|TTCTTAAACACTTCCAGTAACCATGAAAACTCAGACTTGGAAATGCCTT"
### ACC_M9, YVPSYDPSSPQTSQ | FLNTSSNHENSDLE, break points: 14120439 NFIB	135520046 MYB
f6="TACTCTGAAGAACTATGTACCTTCTTATGACCCATCCAGTCCACAAACCAGCCAG|TTCTTAAACACTTCCAGTAACCATGAAAACTCAGACTTGGAAATGCCTTCTTTA"
#### ACC_M9, NLLEFAETLQFIDS | SWYLG* , break points: 135517140 MYB	14088325 NFIB
f7="GGGCACCATTCTGGATAATGTTAAGAACCTCTTAGAATTTGCAGAAACACTCCAATTTATAGATTCT|TCCTGGTACCTGGGCTAGCTTGGTTCCTTTCCAAGTGTCAAATAGGACACCCATCTTACCGGCCAATGTCCAAAATTACGGTTT"
#### ACC_M1, MSTENELKGQQVLP | LRICDWTMNQNGRH, break points:  135515598 MYB 14102509 NFIB
f8="AATTGCTCCTAATGTCAACCGAGAATGAGCTAAAAGGACAGCAGGTGCTACCA|CTGAGGATTTGTGACTGGACCATGAATCAAAACGGCAGGCATTTATACCCCAGTACCAGTG"
#### ACC_M1, *GEVMMYSPICLTQ | TQNHTCSYPGWHST, break points:  14313481 NFIB 135516886 MYB, split reads:10, span reads:7
f9="ATGTTCTCAAAGCATTTACAGTACCTAAAAACAGGTCCCTGGCGAGCCCCTTGCA|GCTGAGGATTTGTGACTGGACCATGAATCAAAACGGCAGGCATTTA"

fusionSeq=f9

## Break point position
breakPos <- regexpr("\\|",fusionSeq)[1]
selSeq1 <- substr(fusionSeq,breakPos-lenAA*3,breakPos-1)
selSeq2 <- substr(fusionSeq,breakPos+1,breakPos+1+lenAA*3)
predictedAA1<-c2s(translate(s2c(selSeq1)))
print(selSeq1)
if (nchar(selSeq1) %%3 != 0){
  print("Error in sequence extraction")
}
predictedAA2<-c2s(translate(s2c(selSeq2)))
print(selSeq2)
predictedAA <- c2s(translate(s2c(paste(selSeq1,selSeq2,sep=""))))
print(predictedAA1)
print(predictedAA2)

print(predictedAA)
print(paste(selSeq1,selSeq2,predictedAA1,predictedAA2))
